docs(README): add 'Export Multiple Conversations' section
pionxzh/chatgpt-exporter pull request #225
Opened 2024-03-19 20:51 UTC by peterkaminski

Adds a section about the "Export Conversations" dialog to `README.md`. Briefly describes the various controls, particularly the "Archive" button, added in #198.

No translations added to `README_ID.md`, `README_KR.md`, or `README_TR.md`.

2024-03-21 11:53 UTC, pionxzh commented
Wow, thanks for this.

2024-03-21 12:16 UTC, pionxzh requested changes

2024-03-21 12:16 UTC, pionxzh commented on README.md
> +Choose the format you want to export to using the format pull-down selector under the list of your conversations at the left. You can choose from the following formats.
```suggestion
Select your export format from the dropdown on the bottom left. You can choose from the following formats.
```

2024-03-22 04:28 UTC, peterkaminski commented
Nice rewording, thanks!

2024-03-22 12:46 UTC, merged